export default [
  {
    state: 'Currently reading / To read',
    books: [
      { title: 'Roger Penrose & Stephen Hawking - The Nature of Space and Time' },
      { title: 'Stephen Hawking - Black Holes and Baby Universes and Other Essays' },
      { title: 'Stephen Hawking - The Large Scale Structure of Space-Time' },
      { title: 'Stephen Hawking - My Brief History' },
      { title: '...TBU...' },
    ],
  },
  {
    state: '2021',
    books: [
      { title: 'Dan Simmons - Hyperion' },
      // { title: 'Jason M. Hough & K.C. Alexander - Mass Effect Andromeda: Nexus Uprising' },
      { title: 'Ахманов Михаил - Среда обитания' },
      { title: '...TBU...' },
    ],
  },
  {
    state: '2020',
    books: [
      { title: 'Leonard Mlodinow & Stephen Hawking - A Briefer History of Time' },
      { title: 'Leonard Mlodinow & Stephen Hawking - The Grand Design' },
      { title: 'Andrzej Sapkowski - The Witcher: The Last Wish' },
      { title: 'William Shakespeare - The Merchant of Venice' },
    ],
  },
  {
    state: '2019',
    books: [
      { title: 'Drew Karpyshyn - Mass Effect: Retribution' },
      { title: 'Drew Karpyshyn - Mass Effect: Ascension' },
      { title: 'Drew Karpyshyn - Mass Effect: Revelation' },
      { title: 'Antoine de Saint-Exupéry - The Little Prince' },
      { title: 'George Orwell - Animal Farm' },
    ],
  },
  {
    state: '2018',
    books: [
      { title: 'Джордж Оруэлл - 1984' },
      { title: 'Грэй Джон - Мужчины с Марса, женщины с Венеры' },
      { title: 'Макс Фрай - Книга огненных страниц' },
      { title: 'Евгений Перов - Подарок судьбы' },
      { title: 'Walls Craig - Spring Boot in Action' },
      { title: 'Владислав Крапивин - Кораблики, или Помоги мне в пути' },
    ],
  },
  {
    state: '2017',
    books: [
      { title: 'McConnell Steve - Code Complete' },
      { title: 'Goodliffe Pete - Code Craft: The Practice of Writing Excellent Code' },
      { title: 'Murakami Haruki - The Dancing Dwarf' },
      { title: 'Murakami Haruki - What I Talk About When I Talk About Running' },
      { title: 'Murakami Haruki - 1Q84' },
      { title: 'Murakami Haruki - Sputnik Sweetheart' },
      { title: 'Murakami Haruki - Tokyo Legends' },
      { title: 'Murakami Haruki - Colorless Tsukuru Tazaki and His Years of Pilgrimage' },
      { title: 'Murakami Haruki - Kafka on the Shore' },
      { title: 'Владимирович Овчинников - Ветка сакуры' },
      { title: 'Argyle Michael - The Psychology of Happiness' },
      { title: 'Golden Christie - Rise of the Horde' },
      { title: 'Bennett Arnold - How to Live on 24 Hours a Day' },
      { title: 'Carnegie Dale - How to Win Friends and Influence People' },
      { title: 'Schildt Herbert - Java: The Complete Reference' },
    ],
  },
  {
    state: 'Cannot recall years',
    books: [
      { title: 'Paolini Christopher - Eragon' },
      { title: 'Paolini Christopher - Eragon: Eldest' },
      { title: 'Paolini Christopher - Eragon: Brisingr' },
      { title: 'Paolini Christopher - Eragon: Inheritance' },
      { title: 'Goodkind Terry - Wizard\'s First Rule' },
      { title: 'Николай Гоголь - Нос' },
      { title: 'Hailey Arthur - Airport' },
      { title: 'Wyndham John - The Day of the Triffids' },
      { title: 'Hemingway Ernest - The Old Man and the Sea' },
      { title: 'Rowling, J.K. - Harry Potter and the Sorcerer\'s Stone' },
      { title: 'Rowling, J.K. - Harry Potter and the Chamber of Secrets' },
      { title: 'Rowling, J.K. - Harry Potter and the Prisoner of Azkaban' },
      { title: 'Rowling, J.K. - Harry Potter and the Goblet of Fire' },
      { title: 'Rowling, J.K. - Harry Potter and the Order of the Phoenix' },
      { title: 'Rowling, J.K. - Harry Potter and the Half-Blood Prince' },
      { title: 'Rowling, J.K. - Harry Potter and the Deathly Hallows' },
      { title: 'Rowling, J.K. - Harry Potter and the cursed child' },
    ],
  },
]
